name: Agent Portal Build
on: [push]

jobs:
  build_nuget:
    name: Build Node App
    runs-on: ubuntu-latest
    steps:      
    - name: checkout-repo
      uses: actions/checkout@v2
      with:
        clean: 'true'

    - name: print-directory 
      run: ls -la
